/** @type {import('tailwindcss').Config} */
// Design tokens ported from the "Obsidian Atelier" design system (obsidian_atelier/DESIGN.md).
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.js'],
  theme: {
    extend: {
      colors: {
        'on-error': '#690005',
        tertiary: '#c0c1ff',
        'on-secondary-fixed-variant': '#474744',
        'primary-fixed-dim': '#c8c6c5',
        'surface-container-lowest': '#0d0e0f',
        'primary-container': '#101010',
        'on-tertiary-fixed-variant': '#2623d1',
        error: '#ffb4ab',
        'primary-fixed': '#e5e2e1',
        'secondary-container': '#494946',
        'on-secondary-container': '#b9b8b4',
        'on-surface-variant': '#c4c7c7',
        'inverse-surface': '#e3e2e2',
        'on-background': '#e3e2e2',
        surface: '#121414',
        'secondary-fixed': '#e4e2dd',
        'inverse-primary': '#5f5e5e',
        'on-tertiary-container': '#656aff',
        'surface-dim': '#121414',
        'on-error-container': '#ffdad6',
        'surface-container-high': '#292a2a',
        'on-primary-fixed-variant': '#474646',
        'secondary-fixed-dim': '#c8c6c2',
        'on-tertiary-fixed': '#05006c',
        'on-primary-fixed': '#1c1b1b',
        'tertiary-fixed': '#e1e0ff',
        'on-primary': '#313030',
        'surface-container': '#1e2020',
        primary: '#c8c6c5',
        'inverse-on-surface': '#2f3131',
        'tertiary-container': '#02004b',
        outline: '#8e9192',
        'surface-tint': '#c8c6c5',
        'tertiary-fixed-dim': '#c0c1ff',
        'on-primary-container': '#7d7c7b',
        'surface-container-low': '#1a1c1c',
        background: '#121414',
        secondary: '#c8c6c2',
        'on-secondary': '#30312e',
        'error-container': '#93000a',
        'surface-variant': '#343535',
        'on-secondary-fixed': '#1b1c19',
        'on-surface': '#e3e2e2',
        'outline-variant': '#444748',
        'surface-bright': '#38393a',
        'on-tertiary': '#0d00aa',
        'surface-container-highest': '#343535',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'gutter-mobile': '1rem',
        gutter: '1.5rem',
        'margin-desktop': '4rem',
        'space-xl': '3rem',
        'space-sm': '0.5rem',
        'gutter-desktop': '2.5rem',
        margin: '2rem',
        'space-md': '1rem',
        'space-lg': '1.75rem',
        'margin-mobile': '1.25rem',
        'space-xs': '0.25rem',
      },
      fontFamily: {
        'headline-lg': ['Syne', 'sans-serif'],
        'headline-md': ['Syne', 'sans-serif'],
        'headline-sm': ['Syne', 'sans-serif'],
        'display-xl': ['Syne', 'sans-serif'],
        'display-xl-mobile': ['Syne', 'sans-serif'],
        'display-lg': ['Syne', 'sans-serif'],
        'display-lg-mobile': ['Syne', 'sans-serif'],
        'headline-lg-mobile': ['Syne', 'sans-serif'],
        'body-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'body-md': ['"Hanken Grotesk"', 'sans-serif'],
        'body-sm': ['"Hanken Grotesk"', 'sans-serif'],
        'label-md': ['"Space Mono"', 'monospace'],
        'label-sm': ['"Space Mono"', 'monospace'],
      },
      fontSize: {
        'display-xl': ['96px', { lineHeight: '96px', letterSpacing: '-0.04em', fontWeight: '800' }],
        'display-xl-mobile': ['48px', { lineHeight: '52px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'display-lg': ['64px', { lineHeight: '68px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '500' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.12em', fontWeight: '400' }],
      },
      keyframes: {
        marquee: {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(-100%)' },
        },
      },
    },
  },
  plugins: [],
};
